- name: Create .aws if it does not exist
  become: true
  file:
    path: "{{ target_dir }}"
    state: directory
    mode: '0755'  # Permissions set to 755 to allow read and execute access by others

# Add the aws config file to use to the roles/files directory
- name: Copy aws config
  become: true
  ansible.builtin.copy:
    src: "config"
    dest: "{{ target_dir }}/config"

# Add the aws credentials file to use to the roles/files directory
- name: Copy aws credentials
  become: true
  ansible.builtin.copy:
    src: "credentials"
    dest: "{{ target_dir }}/credentials"

- name: Delete existing kubernetes secret
  shell: kubectl --server=https://pu.mk8scluster-e00a57k7rk5jp2fv7v.mk8s.eu-north1.nebius.cloud:443 delete secret {{ secret_name }} -n ais --ignore-not-found
    
- name: Create kubernetes secret
  shell: "kubectl create secret -n ais generic {{ secret_name }} \
  --from-file=config={{ target_dir }}/config \
  --from-file=credentials={{ target_dir }}/credentials"

- name: Clean up copied files
  become: true
  file:
    path: "{{ target_dir }}"
    state: absent