- name: Get certificate value from K8s secret
  shell: kubectl --server=https://pu.mk8scluster-e00a57k7rk5jp2fv7v.mk8s.eu-north1.nebius.cloud:443 get secret -n {{cluster}} {{ca_cert_secret}} -o jsonpath="{.data['ca\.crt']}" | base64 --decode
  register: cacert

- name: Copy value of cacert to local file
  copy:
    content: "{{ cacert.stdout }}"
    dest: "{{ cacert_file }}"
  delegate_to: localhost