- name: Copy PV scripts/templates
  become: true
  copy:
    src: "{{ item }}"
    dest: "/tmp"
    mode: 0777
  loop:
    - "create-pvs.sh"
    - "pv.template.yaml"
  when: redeploy is not defined

- name: Set k8s nodes list based on 'new_node' if defined
  set_fact:
    nodes: "{{ new_node }}"
  when: new_node is defined

- name: Set k8s nodes list based on hostname
  set_fact:
    nodes: "{{ groups[cluster] | join(' ') }}"
  when: new_node is not defined and node_name is not defined

- name: Set k8s nodes list based on 'node_name' variable (e.g. "-e node_name=ansible_host" to use the node's IP)
  set_fact:
    nodes: "{{ groups[cluster] | map('extract', hostvars, node_name) | join(' ') }}"
  when: new_node is not defined and node_name is defined

# First, fetch create-pvs.sh script from the remote to the jumphost
- name: Copy create-pvs.sh to jumphost
  fetch:
    src: "/tmp/create-pvs.sh"
    dest: "/tmp/create-pvs.sh"
    flat: yes
  when: redeploy is not defined

# Also fetch the template file
- name: Copy pv.template.yaml to jumphost
  fetch:
    src: "/tmp/pv.template.yaml"
    dest: "/tmp/pv.template.yaml"
    flat: yes
  when: redeploy is not defined

- name: Label nodes
  shell: kubectl label nodes {{ nodes }} nvidia.com/ais-proxy="{{ cluster }}" nvidia.com/ais-target="{{ cluster }}"
  register: labelout
  changed_when: "'labeled' in labelout.stdout and 'not labeled' not in labelout.stdout"
  when: redeploy is not defined
  delegate_to: localhost

- name: Create PVs
  shell: "NAMESPACE={{ cluster }} MPATH_SIZE={{ ais_mpath_size }} MPATHS={{ ais_mpaths | join(' ') | quote }} NODES={{ nodes | quote }} TARGET_INDEX={{ target_index | default('0') }} /tmp/create-pvs.sh"
  register: createpvsout
  changed_when: "'configured' in createpvsout.stdout or 'created' in createpvsout.stdout"
  when: redeploy is not defined
  delegate_to: localhost