- name: Copy CA Creation yaml
  become: true
  template:
    src: "ca.yaml.j2"
    dest: "https_ca.yaml"
    mode: 0777
    lstrip_blocks: true
    
# Fetch the YAML to jumphost
- name: Copy https_ca.yaml to jumphost
  fetch:
    src: "https_ca.yaml"
    dest: "/tmp/https_ca.yaml"
    flat: yes

- name: Create CA
  command: "kubectl apply -f /tmp/https_ca.yaml"
  delegate_to: localhost

- name: Delete existing cert if it exists
  shell: kubectl delete secret {{ tls_secret }} -n ais --ignore-not-found
  delegate_to: localhost

- name: Use CA to issue cert
  become: true
  template:
    src: "cert.yaml.j2"
    dest: "https_cert.yaml"
    mode: 0777
    lstrip_blocks: true
    
# Fetch the YAML to jumphost
- name: Copy https_cert.yaml to jumphost
  fetch:
    src: "https_cert.yaml"
    dest: "/tmp/https_cert.yaml"
    flat: yes
    
- name: Create Cert
  command: "kubectl apply -f /tmp/https_cert.yaml"
  delegate_to: localhost