- name: Copy CA Creation yaml
  become: true
  template:
    src: "ca.yaml.j2"
    dest: "https_ca.yaml"
    mode: 0777
    lstrip_blocks: true
    
- name: Create CA
  command: "kubectl apply -f https_ca.yaml"

- name: Delete existing cert if it exists
  shell: kubectl --server=https://pu.mk8scluster-e00a57k7rk5jp2fv7v.mk8s.eu-north1.nebius.cloud:443 delete secret {{ tls_secret }} -n ais --ignore-not-found

- name: Use CA to issue cert
  become: true
  template:
    src: "cert.yaml.j2"
    dest: "https_cert.yaml"
    mode: 0777
    lstrip_blocks: true
    
- name: Create Cert
  command: "kubectl apply -f https_cert.yaml"