- name: Ensure target directory exists
  become: true
  file:
    path: "{{ target_dir }}"
    state: directory

- name: Copy GCP credentials JSON file to target directory
  become: true
  ansible.builtin.copy:
    src: "gcp.json"
    dest: "{{ target_dir }}/gcp.json"

- name: Remove existing Kubernetes secret if it exists
  shell: kubectl --server=https://pu.mk8scluster-e00a57k7rk5jp2fv7v.mk8s.eu-north1.nebius.cloud:443 delete secret {{ secret_name }} -n ais --ignore-not-found
    
- name: Create new Kubernetes secret from GCP credentials file
  shell: "kubectl create secret -n ais generic {{ secret_name }} \
  --from-file=gcp.json={{ target_dir }}/gcp.json"

- name: Clean up - remove target directory and its contents
  become: true  
  file:
    path: "{{ target_dir }}"
    state: absent


